// src/lib/components/course/list.svelte
<script lang='ts'>
  import Card from '$lib/components/course/card.svelte'
  import { courses as courseSchema } from '$lib/server/db/schema'

  type Props = {
    courses: typeof courseSchema.$inferSelect[]
    activeCourseId?: number
  }

  const { courses, activeCourseId }: Props = $props()

  const onClick = (id: number) => {
    // eslint-disable-next-line no-console
    console.log(id)
  }
</script>

<div class='pt-6 grid grid-cols-2 lg:grid-cols-[repeat(auto-fill,minmax(210px,1fr))] gap-4'>
  {#each courses as course}
    <Card
      id={course.id}
      title={course.title}
      imageSrc={course.imageSrc}
      disabled={false}
      active={course.id === activeCourseId}
      onClick={onClick}
    />
  {/each}
</div>

// components/courses/list.vue
<script lang="ts" setup>
import { toast } from 'vue-sonner'

import Card from './card.vue'
import type { courses, userProgress } from '~/db/schema'

const props = defineProps<{
  courses: typeof courses.$inferSelect[]
  activeCourseId?: typeof userProgress.$inferSelect.activeCourseId
}>()

const router = useRouter()

const loading = ref(false)

async function onClick(id: number) {
  if (id === props.activeCourseId)
    return router.push('/learn')

  const { error } = await useFetch('/api/user-progress', {
    method: 'PUT',
    body: {
      courseId: id,
    },
  })

  if (error.value)
    toast.error('Something went wrong')
}
</script>

<template>
  <div class="pt-6 grid grid-cols-2 lg:grid-cols-[repeat(auto-fill,minmax(210px,1fr))] gap-4">
    <Card
      v-for="course in props.courses"
      :id="course.id"
      :key="course.id"
      :title="course.title"
      :image-src="course.imageSrc"
      :disabled="loading"
      :active="course.id === activeCourseId"
      @click="onClick(course.id)"
    />
  </div>
</template>
